# Generated by Django 4.1.4 on 2022-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', models.CharField(max_length=12)),
                ('search_area', models.CharField(max_length=256, verbose_name='адрес')),
            ],
        ),
    ]
